export { ClientModule } from './client/client.module'
export { CustomerModule } from './customer/customer.module'
export { GroupModule } from './group/group.module'
export { GroupScheduleModule } from './group-schedule/group-schedule.module'
export { GroupStyleModule } from './group-style/group-style.module'
export { GroupStyleVariantModule } from './group-style-variant/group-style-variant.module'
export { PassModule } from './pass/pass.module'
export { PassTemplateModule } from './pass-template/pass-template.module'
export { StaffMemberModule } from './staff-member/staff-member.module'
export { StudioModule } from './studio/studio.module'
export { SubscribtionModule } from './subscribtion/subscribtion.module'
export { TrainingModule } from './training/training.module'
export { TrainingSignupModule } from './training-signup/training-signup.module'
export { UserProfileModule } from './user-profile/user-profile.module'
export { GroupAgeRestrictionModule } from './group-age-restriction/group-age-restriction.module'
export { GroupAgeRestrictionExeptionModule } from './group-age-restriction-exeption/group-age-restriction-exeption.module'
export { FeedbackNotificationModule } from './feedback-notifications/feedback-notifications.module'

export {PaymentModule} from './payment/payment.module'
export { StudioPayoutRuleModule } from './studio-payout-rule/studio-payout-rule.module'
