-- Custom SQL migration file, put your code below! --
-- Fixes the training times generated by 0079 (EraStudio only).
-- 0079 built dates with generate_series(date, date, interval), which returns timestamptz, so
-- AT TIME ZONE 'Europe/Kyiv' shifted them by twice the Kyiv offset (17:00 was stored as 23:00 Kyiv).
-- The intended day is the UTC date of the stored value (the DB runs in UTC; every scheduled time + offset < 24h).
-- Idempotent: a correctly stored training maps to itself.
DO $$
DECLARE
  sid uuid;
  n integer;
  tz constant text := 'Europe/Kyiv';
  changed_groups constant integer[] := ARRAY[4, 5, 8, 11, 12, 14, 24];
BEGIN
  SELECT count(*) INTO n FROM studio WHERE title = 'EraStudio';
  IF n = 0 THEN
    RAISE NOTICE 'EraStudio not found, skipping';
    RETURN;
  ELSIF n > 1 THEN
    RAISE EXCEPTION 'More than one studio titled EraStudio';
  END IF;
  SELECT id INTO sid FROM studio WHERE title = 'EraStudio';

  IF EXISTS (
    SELECT 1 FROM training t
    JOIN group_schedule gs ON gs.id = t.group_schedule_id
    JOIN group_schedule_day d ON d.id = gs.group_schedule_day_id
    WHERE t.group_id = ANY (changed_groups) AND t.date > now()
      AND extract(dow FROM (t.date AT TIME ZONE 'UTC')::date) <> d.day_index
  ) THEN
    RAISE EXCEPTION 'A future training does not match its schedule weekday';
  END IF;

  UPDATE training t
  SET date = ((t.date AT TIME ZONE 'UTC')::date + gs.time::time) AT TIME ZONE tz
  FROM group_schedule gs, "group" g
  WHERE gs.id = t.group_schedule_id
    AND g.id = t.group_id
    AND g.studio_id = sid
    AND t.group_id = ANY (changed_groups)
    AND t.date > now();
  GET DIAGNOSTICS n = ROW_COUNT;
  RAISE NOTICE 'Fixed % trainings', n;
END $$;
