export const BUTTON_PATTERNS = {
  YES: '✅ Так',
  CONFIRM: '✅ Підтвердити',
  VERIFY: '✅ Верифікувати',
  AGREE: '✅ Погоджуюсь',
  SELECT: '✅ Обрати',
  REJECT: '🙅‍♀️ Відхилити',
  BLOCK: '🚫 Заблокувати',
  CANCEL: '❌ Ні',
  BACK: '⬅️ Назад',
  EXIT: '🚪 Вийти',
  START: '🏠 Головне меню',
  RULES: '‼️ПРАВИЛА ТА УМОВИ‼️',
  REGISTER_AS_GUEST: '👤 Продовжити як гість',
  REGISTER_AS_CLIENT: '🧚‍♀️ Зареєструватись як клієнт',
  REGISTER_AS_TRAINER: '👨‍🏫 Зареєструватись як тренер',
  SCHEDULE: '📝 Записатись на тренування',
  ADD_REVIEW: '⭐ Залишити відгук',
  REMIND_LATER: '⏰ Нагадати пізніше',
  ACTIVE_SCHEDULES: '✅ Мої активні записи',
  PASS_INFO: '🎫 Інформація про абонемент',
  PAYMENT: '💳 Оплатити абонемент (реквізити)',
  REGISTER_FINISH: '✅ Завершити реєстрацію',
  REQUESTS: '🔸 Запити на верифікацію',
  BACK_TO_MAIN_ADMIN_MENU: '🔙 Назад до меню адміністратора',
  BACK_TO_MAIN_TRAINER_MENU: '🔙 Назад до меню тренера',
  GROUP_TRAININGS: '📝 Інформація про тренування',
  PAYOUT_CALCULATIONS: '💰 Нарахування оплати',
  UPCOMING_TRAININGS: '🗓️ Найближчі тренування',
  STAFF: '👨‍🏫 Персонал',
  GROUPS: '👯‍♀️ Групи',
  CLIENTS: '💃 Клієнти',
  GROUP_PASS_TYPE: '👥 Груповий абонемент',
  INDIVIDUAL_PASS_TYPE: '👤 Індивідуальний абонемент',
} as const
