export const BUTTON_PATTERNS = {
  YES: '✅ Так',
  CONFIRM: '✅ Підтвердити',
  VERIFY: '✅ Верифікувати',
  AGREE: '✅ Погоджуюсь',
  ACTIVATE: '✅ Активувати',
  SELECT: '✅ Обрати',
  REJECT: '🙅‍♀️ Відхилити',
  BLOCK: '🚫 Заблокувати',
  CANCEL: '❌ Ні',
  BACK: '⬅️ Назад',
  EXIT: '🚪 Вийти',
  CLOSE: '✖️ Закрити',
  ARCHIVE: '📦 Архівувати',
  UNARCHIVE: '📤 Розархівувати',
  START: '🏠 Головне меню',
  VERIFY_WITHOUT_PASS: '🟡 Верифікувати без абонементу',
  RULES: '‼️ПРАВИЛА ТА УМОВИ‼️',
  CANCEL_TRAINING: '🚫 Відмінити тренування',
  ACTIVATE_TRAINING: '✅ Активувати тренування',
  EDIT_PROFILE: '✏️ Редагувати профіль',
  EDIT_NAME: '📝 Змінити ім\'я',
  EDIT_DATE_OF_BIRTH: '🎂 Змінити дату народження',
  EDIT_PHONE: '📞 Змінити номер телефону',
  REGISTER_AS_GUEST: '👤 Продовжити як гість',
  REGISTER_AS_CLIENT: '🧚‍♀️ Зареєструватись як клієнт',
  REGISTER_AS_TRAINER: '👨‍🏫 Зареєструватись як тренер',
  SCHEDULE: '📝 Записатись на тренування',
  SCHEDULE_TO_TRAINING: '✔️ Записати',
  DESCHEDULE_FROM_TRAINING: '➖ Виписати',
  ADD_REVIEW: '⭐ Залишити відгук',
  REMIND_LATER: '⏰ Нагадати пізніше',
  ACTIVE_SCHEDULES: '✅ Мої активні записи',
  ASSIGN_SUBSTITUTE: '👥 Призначити заміну',
  DEASSIGN_SUBSTITUTE: '👥 Відмінити заміну',
  PASS_INFO: '🎫 Інформація про абонемент',
  PASS: '🎫 Абонемент',
  PASS_EDIT_START_DATE: '📆 Змінити дату початку',
  PASS_EDIT_END_DATE: '📆 Змінити дату закінчення',
  PASS_EDIT_LENGTH: '✏️ Редагувати кількість тренувань', // це кількість доступних тренувань
  PAYMENT: '💳 Реквізити для оплати',
  REGISTER_FINISH: '✅ Завершити реєстрацію',
  REQUESTS: '🔸 Запити на верифікацію',
  BACK_TO_MAIN_ADMIN_MENU: '🔙 Назад до меню адміністратора',
  BACK_TO_MAIN_TRAINER_MENU: '🔙 Назад до меню тренера',
  BACK_TO_TRAINING_LIST: '⬅️ Назад до списку тренувань',
  BACK_TO_STAFF_LIST: '⬅️ Назад до списку тренерів',
  BACK_TO_GROUP_LIST: '⬅️ Назад до списку груп',
  GROUP_TRAININGS: '📝 Інформація про тренування',
  PAYOUT_CALCULATIONS: '💰 Нарахування оплати',
  UPCOMING_TRAININGS: '🗓️ Найближчі тренування',
  STAFF: '👨‍🏫 Персонал',
  GROUPS: '👯‍♀️ Групи',
  STAFF_GROUPS: '👯‍♀️ Групи тренера',
  ADD_GROUP_TO_STAFF: '➕ Додати групу',
  REMOVE_GROUP_FROM_STAFF: '➖ Видалити групу',
  CLIENTS: '💃 Клієнти',
  TRAININGS: '🤸‍♂️ Тренування',
  TRAINERS: '👨‍🏫 Тренери',
  GROUP_PASS_TYPE: '👥 Груповий абонемент',
  INDIVIDUAL_PASS_TYPE: '👤 Індивідуальний абонемент',
  SCHEDULES_INFO: '📝 Інформація про записи',
  SEE_DETAILS: '📑 Переглянути деталі',
  INITIATE_PAYOUT: '💸 Виплатити запрлату',
  ACTIVE_SCHEDULES_LIST: '📜 Активні записи',
  CANCELED_SCHEDULES_LIST: '📜 Скасовані записи',
  CLIENT_PASS_BUY: '💵 Купити абонемент',
  CLIENT_PASS_RENEW: '🔁 Поновити абонемент',
} as const
