export const BUTTON_PATTERNS = {
  YES: '✅ Так',
  CONFIRM: '✅ Підтвердити',
  VERIFY: '✅ Верифікувати',
  AGREE: '✅ Погоджуюсь',
  SELECT: '✅ Обрати',
  REJECT: '🙅‍♀️ Відхилити',
  BLOCK: '🚫 Заблокувати',
  CANCEL: '❌ Ні',
  BACK: '⬅️ Назад',
  EXIT: '🚪 Вийти',
  CLOSE: '✖️ Закрити',
  START: '🏠 Головне меню',
  RULES: '‼️ПРАВИЛА ТА УМОВИ‼️',
  CANCEL_TRAINING: '🚫 Відмінити тренування',
  ACTIVATE_TRAINING: '✅ Активувати тренування',
  REGISTER_AS_GUEST: '👤 Продовжити як гість',
  REGISTER_AS_CLIENT: '🧚‍♀️ Зареєструватись як клієнт',
  REGISTER_AS_TRAINER: '👨‍🏫 Зареєструватись як тренер',
  SCHEDULE: '📝 Записатись на тренування',
  SCHEDULE_TO_TRAINING: '✔️ Записати на тренування',
  DESCHEDULE_FROM_TRAINING: '➖ Виписати з тренування',
  ADD_REVIEW: '⭐ Залишити відгук',
  REMIND_LATER: '⏰ Нагадати пізніше',
  ACTIVE_SCHEDULES: '✅ Мої активні записи',
  PASS_INFO: '🎫 Інформація про абонемент',
  PAYMENT: '💳 Оплатити абонемент (реквізити)',
  REGISTER_FINISH: '✅ Завершити реєстрацію',
  REQUESTS: '🔸 Запити на верифікацію',
  BACK_TO_MAIN_ADMIN_MENU: '🔙 Назад до меню адміністратора',
  BACK_TO_MAIN_TRAINER_MENU: '🔙 Назад до меню тренера',
  BACK_TO_TRAINING_LIST: '⬅️ Назад до списку тренувань',
  BACK_TO_STAFF_LIST: '⬅️ Назад до списку тренерів',
  BACK_TO_GROUP_LIST: '⬅️ Назад до списку груп',
  GROUP_TRAININGS: '📝 Інформація про тренування',
  PAYOUT_CALCULATIONS: '💰 Нарахування оплати',
  UPCOMING_TRAININGS: '🗓️ Найближчі тренування',
  STAFF: '👨‍🏫 Персонал',
  GROUPS: '👯‍♀️ Групи',
  STAFF_GROUPS: '👯‍♀️ Групи тренера',
  CLIENTS: '💃 Клієнти',
  TRAININGS: '🤸‍♂️ Тренування',
  TRAINERS: '👨‍🏫 Тренери',
  GROUP_PASS_TYPE: '👥 Груповий абонемент',
  INDIVIDUAL_PASS_TYPE: '👤 Індивідуальний абонемент',
  SCHEDULES_INFO: '📝 Інформація про записи',
  SEE_DETAILS: '📑 Переглянути деталі',
  INITIATE_PAYOUT: '💸 Виплатити запрлату',
  ACTIVE_SCHEDULES_LIST: '📜 Активні записи',
  CANCELED_SCHEDULES_LIST: '📜 Скасовані записи',
} as const
