import { PATTERNS_CLIENT, PATTERNS_COMMON } from './patterns'

export const KEYBOARDS_CLIENT = {
  MAIN_MENU: [
    [PATTERNS_COMMON.SCHEDULE, PATTERNS_CLIENT.ACTIVE_SCHEDULES],
    [PATTERNS_CLIENT.PASS_INFO],
    [PATTERNS_CLIENT.PAYMENT],
    [PATTERNS_COMMON.RULES],
  ],
  REGISTER_AS_CLIENT: [[PATTERNS_COMMON.REGISTER_AS_CLIENT]]
}


export const KEYBOARDS_GUEST = {
  MAIN_MENU: [
    [PATTERNS_COMMON.SCHEDULE],
    [PATTERNS_COMMON.RULES],
  ],
  REGISTER_AS_GUEST: [[PATTERNS_COMMON.REGISTER_AS_GUEST]]
}

export const KEYBOARDS_SCENE = {
  COMMON: {
    BACK_EXIT: [[PATTERNS_COMMON.BACK], [PATTERNS_COMMON.EXIT]],
    EXIT: [[PATTERNS_COMMON.EXIT]],
    CONFIRM: [[PATTERNS_COMMON.CONFIRM]],
  }
}

