import { PATTERNS_ADMIN, PATTERNS_CLIENT, PATTERNS_COMMON, PATTERNS_SCENE } from './patterns'

export const KEYBARODS_COMMON = {
  REGISTER_AS: [[PATTERNS_COMMON.REGISTER_AS_GUEST], [PATTERNS_COMMON.REGISTER_AS_CLIENT], [PATTERNS_COMMON.REGISTER_AS_TRAINER]],
}

export const KEYBOARDS_CLIENT = {
  MAIN_MENU: [
    [PATTERNS_COMMON.SCHEDULE, PATTERNS_CLIENT.ACTIVE_SCHEDULES],
    [PATTERNS_CLIENT.PASS_INFO],
    [PATTERNS_CLIENT.PAYMENT],
    [PATTERNS_COMMON.RULES],
  ],
}

export const KEYBOARDS_GUEST = {
  MAIN_MENU: [[PATTERNS_COMMON.SCHEDULE], [PATTERNS_COMMON.RULES], [PATTERNS_COMMON.REGISTER_AS_CLIENT]],
}

export const KEYBOARDS_TRAINER = {
  MAIN_MENU: [[PATTERNS_COMMON.SCHEDULE], [PATTERNS_COMMON.RULES], [PATTERNS_COMMON.REGISTER_AS_CLIENT]],
}

export const KEYBOARDS_ADMIN = {
  MAIN_MENU: [[PATTERNS_ADMIN.REQUESTS], [PATTERNS_ADMIN.STAFF], [PATTERNS_ADMIN.GROUPS], [PATTERNS_ADMIN.CLIENTS]],
}

export const KEYBOARDS_SCENE = {
  COMMON: {
    BACK_EXIT: [[PATTERNS_COMMON.BACK], [PATTERNS_COMMON.EXIT]],
    EXIT: [[PATTERNS_COMMON.EXIT]],
    CONFIRM: [[PATTERNS_COMMON.BACK], [PATTERNS_COMMON.CONFIRM]],
  },
  VERIFY_CLIENT: {
    PASS_TYPE: [
      [PATTERNS_SCENE.VERIFY_CLIENT.GROUP_PASS_TYPE],
      [PATTERNS_SCENE.VERIFY_CLIENT.INDIVIDUAL_PASS_TYPE],
      [PATTERNS_COMMON.EXIT],
    ],
  },
}
