import { InferSelectModel } from 'drizzle-orm'
import * as schemas from '../schemas'

export type ClientSelectModel = InferSelectModel<typeof schemas.client>
export type CustomerSelectModel = InferSelectModel<typeof schemas.customer>
export type GroupScheduleDaySelectModel = InferSelectModel<typeof schemas.groupScheduleDay>
export type GroupScheduleSelectModel = InferSelectModel<typeof schemas.groupSchedule>
export type GroupStyleSelectModel = InferSelectModel<typeof schemas.groupStyle>
export type GroupAgeRestrictionSelectModel = InferSelectModel<typeof schemas.groupAgeRestriction>
export type GroupAgeRestrictionExceptionSelectModel = InferSelectModel<typeof schemas.groupAgeRestrictionException>
export type GroupStyleVariantSelectModel = InferSelectModel<typeof schemas.groupStyleVariant>
export type GroupSelectModel = InferSelectModel<typeof schemas.group>
export type PassSelectModel = InferSelectModel<typeof schemas.pass>
export type StaffMemberSelectModel = InferSelectModel<typeof schemas.staffMember>
export type StudioSelectModel = InferSelectModel<typeof schemas.studio>
export type SubscribtionPlanSelectModel = InferSelectModel<typeof schemas.subscribtionPlan>
export type SubscribtionSelectModel = InferSelectModel<typeof schemas.subscribtion>
export type TrainingSignupSelectModel = InferSelectModel<typeof schemas.trainingSignup>
export type TrainingSelectModel = InferSelectModel<typeof schemas.training>
export type UserProfileSelectModel = InferSelectModel<typeof schemas.userProfile>
export type PassTemplateSelectModel = InferSelectModel<typeof schemas.passTemplate>
export type PassTemplateAgeRestrictionSelectModel = InferSelectModel<typeof schemas.passTemplateAgeRestriction>
export type PassTemplateAgeRestrictionExceptionSelectModel = InferSelectModel<typeof schemas.passTemplateAgeRestrictionException>
export type PaymentSelectModel = InferSelectModel<typeof schemas.payment>
export type StudioPayoutRuleSelectModel = InferSelectModel<typeof schemas.studioPayoutRule>
export type FeedbackNotificationSelectModel = InferSelectModel<typeof schemas.feedbackNotification>
export type PassActivationRequestSelectModel = InferSelectModel<typeof schemas.passActivationRequest>
